# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: file-contents-sorter
        files: ips.txt
        args: [--unique]
-   repo: local
    hooks:
    -   id: custom-gen-nginx-conf
        name: Generate nginx configuration
        entry: tools/nginx-conf-gen.sh
        language: script
        always_run: true
    -   id: custom-gen-apache-conf
        name: Generate apache configuration
        entry: tools/apache-conf-gen.sh
        language: script
        always_run: true
