# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: file-contents-sorter
        files: ips.txt
        args: [--unique]
-   repo: local
    hooks:
    -   id: realip-nginx-conf-gen
        name: Generate nginx realip configuration
        entry: tools/realip-nginx-conf-gen.sh
        language: script
        always_run: true
    -   id: access-nginx-conf-gen
        name: Generate nginx access configuration
        entry: tools/access-nginx-conf-gen.sh
        language: script
        always_run: true
    -   id: realip-apache-conf-gen
        name: Generate apache realip configuration
        entry: tools/realip-apache-conf-gen.sh
        language: script
        always_run: true
    -   id: htaccess-conf-gen
        name: Generate apache htaccess configuration
        entry: tools/htaccess-conf-gen.sh
        language: script
        always_run: true
    -   id: iptables-cli-gen
        name: Generate iptables cli command list
        entry: tools/iptables-cli-gen.sh
        language: script
        always_run: true
    -   id: ipset-gen
        name: Generate iptables ipset list
        entry: tools/ipset-gen.sh
        language: script
        always_run: true
